import './globals.css';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Roboto, Noto_Sans_KR } from 'next/font/google';

const RobotoFont = Roboto({
  weight: ['400', '700'],
  style: 'normal',
  variable: '--font-roboto',
  subsets: ['latin'],
  display: 'swap',
});

const NotoSansKRFont = Noto_Sans_KR({
  weight: ['400', '700'],
  style: 'normal',
  variable: '--font-noto-sans-kr',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Demo',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`${RobotoFont.variable} ${NotoSansKRFont.variable}`}>
        <header className="flex justify-between items-center p-2 border-b border-b-blue-900 font-roboto">
          <h1>
            <Link href="/">Demo Note App</Link>
          </h1>
          <nav className="flex gap-2">
            <Link href="/products">Products</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
